/*******************************************************************************************
*
*   raylib [textures] example - Load textures from raw data
*
*   Example complexity rating: [★★★☆] 3/4
*
*   NOTE: Images are loaded in CPU memory (RAM); textures are loaded in GPU memory (VRAM)
*
*   Example originally created with raylib 1.3, last time updated with raylib 3.5
*
*   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
*   BSD-like license that allows static linking with closed source software
*
*   Copyright (c) 2015-2025 Ramon Santamaria (@raysan5)
*
********************************************************************************************/

import {BROWN, BeginDrawing, ClearBackground, CloseWindow, DrawText, DrawTexture, EndDrawing, Fade, GOLD,
    Image, InitWindow, LoadImageRaw, LoadTextureFromImage, ORANGE, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
    RAYWHITE,
    SetTargetFPS, UnloadImage, UnloadTexture, WHITE, WindowShouldClose } from "rayjs:raylib";

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const screenWidth = 800;
    const screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture from raw data");

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

    // Load RAW image data (512x512, 32bit RGBA, no file header)
    let fudesumiRaw = LoadImageRaw("resources/fudesumi.raw", 384, 512, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0);
    let fudesumi = LoadTextureFromImage(fudesumiRaw);  // Upload CPU (RAM) image to GPU (VRAM)
    UnloadImage(fudesumiRaw);                                // Unload CPU (RAM) image data

    // Generate a checked texture by code
    let width = 960;
    let height = 480;

    // Dynamic memory allocation to store pixels data (RGBA, 4 bytes per pixel).
    // The C original uses a Color* array; in JS we pack the 4 components
    // manually into a flat Uint8Array since Color is an object, not a number.
    let pixels = new Uint8Array(width*height*4);

    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            // C original uses integer division here; in JS `/` is float, so
            // `(x/32 + y/32) % 2 == 0` almost never matches. Truncate explicitly.
            const color = (((x>>5) + (y>>5)) & 1) == 0 ? ORANGE : GOLD;
            const i = (y*width + x)*4;
            pixels[i    ] = color.r;
            pixels[i + 1] = color.g;
            pixels[i + 2] = color.b;
            pixels[i + 3] = color.a;
        }
    }

    // Load pixels data into an image structure and create texture
    let checkedIm = new Image();
    checkedIm.data = pixels.buffer;             // We can assign pixels directly to data
    checkedIm.width = width;
    checkedIm.height = height;
    checkedIm.format = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8;
    checkedIm.mipmaps = 1;

    let checked = LoadTextureFromImage(checkedIm);
    UnloadImage(checkedIm);         // Unload CPU (RAM) image data (pixels)

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //---------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose()) {   // Detect window close button or ESC key
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawTexture(checked, screenWidth/2 - checked.width/2, screenHeight/2 - checked.height/2, Fade(WHITE, 0.5));
            DrawTexture(fudesumi, 430, -30, WHITE);

            DrawText("CHECKED TEXTURE ", 84, 85, 30, BROWN);
            DrawText("GENERATED by CODE", 72, 148, 30, BROWN);
            DrawText("and RAW IMAGE LOADING", 46, 210, 30, BROWN);

            DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, BROWN);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(fudesumi);    // Texture unloading
    UnloadTexture(checked);     // Texture unloading

    CloseWindow();              // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
}