// Hand-maintained TypeScript declarations for box2d functions that are bridged
// manually in src/box2d_helpers.h rather than generated by bindings/src/index.js.
//
// These functions are marked ignore() in index.js (so the generator skips them
// and lib.js_box2d.d.ts does not declare them), and their JS exports come from
// JS_SetModuleExport calls registered alongside js_box2d_init. This file uses
// TypeScript's module-augmentation behaviour to add their signatures onto the
// "rayjs:box2d" declaration without touching the auto-generated file.
//
// If you add another hand-bridged function in src/box2d_helpers.h, append its
// signature here.

declare module "rayjs:box2d" {
    import type {
        b2WorldId, b2ShapeId,
        b2AABB, b2Vec2, b2QueryFilter, b2ShapeProxy, b2Capsule,
        b2TreeStats, b2PlaneResult, b2Manifold,
    } from "rayjs:box2d"

    // ── Per-call query / cast callbacks (Category B) ─────────────────────────
    // The callback's return value steers the traversal:
    //   OverlapResultFcn  — return true to keep scanning, false to stop.
    //   CastResultFcn     — return -1 to ignore the hit, 0 to stop immediately,
    //                       a fraction in (0,1] to clip the ray to that point
    //                       (closest-hit mode), 1 to continue without clipping.
    //   PlaneResultFcn    — return true to keep collecting planes, false to stop.

    type b2OverlapResultFcn = (shapeId: b2ShapeId) => boolean
    type b2CastResultFcn    = (shapeId: b2ShapeId, point: b2Vec2, normal: b2Vec2, fraction: number) => number
    type b2PlaneResultFcn   = (shapeId: b2ShapeId, plane: b2PlaneResult) => boolean

    /** Overlap an AABB against every shape in the world. Synchronous: the callback
     *  fires only during this call. */
    function b2World_OverlapAABB(worldId: b2WorldId, aabb: b2AABB, filter: b2QueryFilter,
                                 fcn: b2OverlapResultFcn): b2TreeStats

    /** Overlap an arbitrary shape proxy against every shape in the world. */
    function b2World_OverlapShape(worldId: b2WorldId, proxy: b2ShapeProxy, filter: b2QueryFilter,
                                  fcn: b2OverlapResultFcn): b2TreeStats

    /** Cast a ray and report each hit. Use the callback's return value to choose
     *  any-hit / closest-hit / all-hits semantics (see b2CastResultFcn). */
    function b2World_CastRay(worldId: b2WorldId, origin: b2Vec2, translation: b2Vec2,
                             filter: b2QueryFilter, fcn: b2CastResultFcn): b2TreeStats

    /** Cast a shape proxy through the world. Same return-value semantics as CastRay. */
    function b2World_CastShape(worldId: b2WorldId, proxy: b2ShapeProxy, translation: b2Vec2,
                               filter: b2QueryFilter, fcn: b2CastResultFcn): b2TreeStats

    /** Collect every contact plane the mover capsule overlaps. Used after CastMover
     *  to project residual velocity onto walls (character-controller pattern). */
    function b2World_CollideMover(worldId: b2WorldId, mover: b2Capsule, filter: b2QueryFilter,
                                  fcn: b2PlaneResultFcn): void

    // ── Persistent world callbacks (Category C) ──────────────────────────────
    // Pass null/undefined to clear a previously-registered callback. The JS
    // function ref is held for the lifetime of the registration.

    type b2CustomFilterFcn = (shapeIdA: b2ShapeId, shapeIdB: b2ShapeId) => boolean
    type b2PreSolveFcn     = (shapeIdA: b2ShapeId, shapeIdB: b2ShapeId, manifold: b2Manifold) => boolean

    /** Allow or deny a contact pair before the broadphase narrowphase. Called once
     *  per pair and cached — cheap. Return false to disable the pair. */
    function b2World_SetCustomFilterCallback(worldId: b2WorldId, fcn: b2CustomFilterFcn | null): void

    /** Inspect / cancel contacts during solving. Every shape involved must have
     *  shapeDef.enablePreSolveEvents = true at creation. Return false to cancel
     *  the contact for this step. */
    function b2World_SetPreSolveCallback(worldId: b2WorldId, fcn: b2PreSolveFcn | null): void
}
