# Reads all *.js files from LIB_DIR and:
#   1. Writes OUTPUT_FILE (src/js_ext_modules.h) with each file embedded as a
#      uint8_t[] for the rayjs:ext:<stem> built-in module system.
#   2. For each lib/<stem>.d.ts that exists, writes a matching ambient TypeScript
#      declaration in TYPINGS_DIR (bindings/typings/lib.js_ext_<stem>.d.ts) so
#      that "rayjs:ext:<stem>" is fully typed in the IDE.
#      Stale lib.js_ext_*.d.ts files with no matching lib/*.js are removed.
#
# Invoked via CMake -P at configure time (execute_process) and at build time
# (add_custom_command) whenever a lib/*.js file changes.

file(GLOB js_files "${LIB_DIR}/*.js")

# ── 1. Generate src/js_ext_modules.h ─────────────────────────────────────────

set(out
"// Auto-generated by cmake/gen_ext_modules.cmake — do not edit.
// Embeds every lib/*.js file as a built-in rayjs:ext:<name> module.
#pragma once
#include <stddef.h>
#include <stdint.h>

typedef struct { const char *name; const uint8_t *src; size_t size; } JsExtEntry;

")

set(module_names "")

foreach(js_file ${js_files})
    get_filename_component(name "${js_file}" NAME_WE)
    list(APPEND module_names "${name}")

    file(READ "${js_file}" content HEX)
    string(TOLOWER "${content}" content)
    # Convert each hex pair "ab" → "0xab,"
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_bytes "${content}")

    string(APPEND out "static const uint8_t js_ext_${name}_src[] = {${hex_bytes}0x00};\n\n")
endforeach()

string(APPEND out "static const JsExtEntry js_ext_table[] = {\n")
foreach(name ${module_names})
    string(APPEND out "    { \"${name}\", js_ext_${name}_src, sizeof(js_ext_${name}_src) - 1 },\n")
endforeach()
string(APPEND out "    { NULL, NULL, 0 }\n};\n")

file(WRITE "${OUTPUT_FILE}" "${out}")

# ── 2. Generate bindings/typings/lib.js_ext_<name>.d.ts ──────────────────────

# Remove stale generated typings that no longer have a corresponding lib/*.js.
file(GLOB stale_typings "${TYPINGS_DIR}/lib.js_ext_*.d.ts")
foreach(stale IN LISTS stale_typings)
    get_filename_component(stale_name "${stale}" NAME)
    # Extract stem: lib.js_ext_<stem>.d.ts → <stem>
    string(REGEX REPLACE "^lib\\.js_ext_(.+)\\.d\\.ts$" "\\1" stale_stem "${stale_name}")
    list(FIND module_names "${stale_stem}" found_idx)
    if(found_idx EQUAL -1)
        file(REMOVE "${stale}")
    endif()
endforeach()

foreach(name ${module_names})
    set(dts_src "${LIB_DIR}/${name}.d.ts")
    if(EXISTS "${dts_src}")
        file(READ "${dts_src}" dts_content)
        set(typing_out
"// Auto-generated by cmake/gen_ext_modules.cmake — do not edit.
declare module \"rayjs:ext:${name}\" {
${dts_content}}
")
        file(WRITE "${TYPINGS_DIR}/lib.js_ext_${name}.d.ts" "${typing_out}")
    endif()
endforeach()
