name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install raylib build deps
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          libglfw3 libglfw3-dev \
          libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev \
          libwayland-dev libxkbcommon-dev

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} -j

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rayjs-linux-x86_64
        path: rayjs
